### PR TITLE
Add a Github Action for clippy

### PR DESCRIPTION
**Pull request by cyang1**
Not sure if this works as written, hopefully it's possible to test out in a PR.

Will go through and fix all the lints before landing. Feel free to bikeshed clippy arguments.

### CODE REVIEW

**Comment by cyang1** [comment]
Ah hmm, I'm not sure if this can run on generated code, or what it would look like if it did (given that it posts comments onto the diff itself, and those files aren't in the repo).

**Comment by nipunn1313** [comment]
we can make a PR to add generated fioles to the repo so that this sort of thing works.

Alternately - you can generate them in the first step of the clippy project.
Whatever you feel like

**Comment by cyang1** [comment]
Updated to generate in the clippy action, but still not sure what it will look like.

**Comment by ParkMyCar** [comment]
Shoot I totally missed this, I also added a workflow in #136. I'm happy to land whichever 🙂

**Comment by cyang1** [comment]
Looks like #136 is merged, so I'm fine with closing this. This one adds the Github action that posts comments back on the PR, but I'm not sure how well it works with the multiple crate structure in this repo anyhow.

**Pull request closed without merging**
