### PR TITLE
add edition to rust_library

### PR DESCRIPTION
**Pull request by RSMuthu**
Hi,
Please review it and merge the branch.
This my first contribution try.
Please let me know if i have missed out any

### CODE REVIEW

**Comment by RSMuthu** [comment]
I ran cargo for testing ... But getting the following error ..

```
   Compiling glob v0.3.0
error: linker `link.exe` not found
  |
  = note: The system cannot find the file specified. (os error 2)

```
Can you please tell what I am missing ?

**Comment by nipunn1313** [comment]
Hi,

Haven't tested it out on windows - though I suspect it should work just fine.
Googling your error message, I suspect it's a toolchain issue (eg https://stackoverflow.com/questions/55603111/unable-to-compile-rust-hello-world-on-windows-linker-link-exe-not-found)

Thanks for the PR! Looks good!

**Comment by nipunn1313** [comment]
Don't mind the CI failure - I'm still working on getting that up and running!

**Comment by nipunn1313** [comment]
I credited you in the README! Thank you for the contribution.
If I may ask, would you be able to fill out the CLA agreement?
Thanks
https://opensource.dropbox.com/cla/

**Comment by RSMuthu** [comment]
Thanks.
Yes Sure, I have filled it out just now

**Pull request merged**
